
DROP VIEW IF EXISTS monad_auth CASCADE;
DROP TABLE IF EXISTS monad_page CASCADE;
DROP TABLE IF EXISTS monad_page_i18n CASCADE;
DROP TABLE IF EXISTS monad_section CASCADE;
DROP TABLE IF EXISTS monad_section_i18n CASCADE;
DROP TABLE IF EXISTS monad_section_link_page CASCADE;
DROP TABLE IF EXISTS monad_menu CASCADE;
DROP TABLE IF EXISTS monad_menu_i18n CASCADE;
DROP TABLE IF EXISTS monad_menu_item CASCADE;
DROP TABLE IF EXISTS monad_menu_item_i18n CASCADE;
DROP TABLE IF EXISTS monad_query CASCADE;
DROP TABLE IF EXISTS monad_query_id CASCADE;

